"""
    Docs, Embeddings, Database and Retrieves
"""

from langchain_core.tools import tool
from db import chromadb, pgvector
from utils import doc_loader
from llm import gemini

docs = doc_loader.doc_loader()
embeddings = gemini.get_gemini()


retriever = chromadb.chromadb(pages_split=docs[0], persit_directory=docs[1], collection_name=docs[2], embeddings=embeddings['embeddings'])

# retriever = pgvector.pgvectordb(pages_split=docs[0], COLLECTION_NAME=docs[2], embeddings=embeddings['embeddings'])

@tool
def retriever_tool(query: str) -> str:
    """Retrieve relevant documents based on the query."""
    print(f"==== Retriever Tool =====: \n")

    docs = retriever.invoke(query)
    # print(f"Document Generated by tool: {(docs)}")
    if not docs:
        return "No relevant documents found."

    results = []
    
    for i, doc in enumerate(docs):
        results.append(f"Document {i+1}:\n{doc.page_content}\n")
    
    return "\n\n".join(results)